# to validate this file: cat codecov.yml | curl --data-binary @- https://codecov.io/validate
coverage:
  round: nearest
  range: "80...100"
  status:
    project:
      default:
        target: 70%
        threshold: 0%
        informational: true
    patch:
      default:
        target: 80%
        informational: false
